# Generated by Django 5.2.1 on 2025-05-12 16:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen_ejercicio', models.BinaryField(blank=True, null=True)),
                ('tipo_ejercicio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('diagnostico', models.CharField(max_length=50)),
                ('alergias', models.CharField(blank=True, max_length=50)),
                ('medicamentos', models.CharField(blank=True, max_length=50)),
                ('nombre_emergencia', models.CharField(max_length=80)),
                ('contacto_emergencia', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=80, unique=True)),
                ('nivel_autonomia', models.CharField(max_length=50)),
                ('indice_barthel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('terapeuta', 'Terapeuta'), ('otro', 'Otro')], default='terapeuta', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_groups', related_query_name='usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_user_permissions', related_query_name='usuario_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_escala', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapeuta.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo_corto', models.TextField()),
                ('objetivo_largo', models.TextField()),
                ('periodicidad', models.CharField(max_length=25)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapeuta.paciente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('nivel_logro', models.IntegerField()),
                ('comentarios', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapeuta.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapeuta.paciente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True)),
                ('puntaje', models.IntegerField()),
                ('ejercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terapeuta.ejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapeuta.sesion')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terapeuta.tutor'),
        ),
    ]
